import Foundation
import ShekatiCore

enum Localization {
    static func text(_ key: String, language: AppLanguage) -> String {
        NumericInput.latinDigits(language == .arabic ? arabic[key] ?? key : key)
    }

    /// Arabic day counts follow the CLDR plural categories: one, two, few (3–10), many (11–99) and other.
    static func arabicDays(_ count: Int) -> String {
        let value = abs(count)
        switch (value, value % 100) {
        case (1, _): return "يوم واحد"
        case (2, _): return "يومان"
        case (_, 3...10): return "\(value) أيام"
        case (_, 11...99): return "\(value) يومًا"
        default: return "\(value) يوم"
        }
    }

    /// A reminder offset label such as "14 days before" the due date.
    static func daysBefore(_ offset: Int, language: AppLanguage) -> String {
        language == .arabic ? arabicDays(offset) + " قبل الاستحقاق" : "\(offset) days before"
    }

    /// Relative due-date wording for three or more days; today, tomorrow and two days use dedicated keys.
    static func relativeDays(_ distance: Int, language: AppLanguage) -> String {
        let count = abs(distance)
        switch language {
        case .arabic: return (distance < 0 ? "متأخر منذ " : "بعد ") + arabicDays(count)
        case .english: return distance < 0 ? "Overdue by \(count) days" : "In \(count) days"
        }
    }

    static let arabic: [String: String] = [
        "Shekati": "شيكاتي",
        "Home": "الرئيسية",
        "Cheques": "الشيكات",
        "Settings": "الإعدادات",
        "Add cheque": "إضافة شيك",
        "Done": "تم",
        "Cancel": "إلغاء",
        "Save": "حفظ",
        "Save cheque": "حفظ الشيك",
        "Edit": "تعديل",
        "Edit cheque": "تعديل الشيك",
        "Delete": "حذف",
        "Delete cheque": "حذف الشيك",
        "Delete this cheque?": "حذف هذا الشيك؟",
        "Its details, images and scheduled reminders will be removed.": "سيتم حذف معلوماته وصوره وإزالة تنبيهاته المجدولة.",
        "OK": "حسنًا",
        "Add": "إضافة",
        "Apply": "تطبيق",
        "Required": "مطلوب",
        "Required details": "المعلومات المطلوبة",
        "Cheque": "شيك",
        "Cheque details": "تفاصيل الشيك",
        "More details": "تفاصيل إضافية",
        "Scan or add photos": "تصوير أو إضافة صور",
        "Reminder options": "خيارات التذكير",
        "Filters and sort": "تصفية وترتيب",
        "Reorder cheques": "تغيير ترتيب الشيكات",
        "Name and number": "الاسم والرقم",
        "Amount and due date": "المبلغ والاستحقاق",
        "Shown cheques": "الشيكات المعروضة",
        "Cheque number": "رقم الشيك",
        "Cheque number (optional)": "رقم الشيك (اختياري)",
        "No.": "رقم",
        "Incoming": "وارد",
        "Outgoing": "صادر",
        "Incoming cheque": "شيك وارد",
        "Outgoing cheque": "شيك صادر",
        "Direction": "نوع الشيك",
        "Amount": "المبلغ",
        "Name": "الاسم",
        "Due date": "تاريخ الاستحقاق",
        "Issue date": "تاريخ الإصدار",
        "Add issue date": "إضافة تاريخ الإصدار",
        "Bank": "البنك",
        "Bank (optional)": "البنك (اختياري)",
        "Branch": "الفرع",
        "Branch (optional)": "الفرع (اختياري)",
        "Payee": "المستفيد",
        "Payee (optional)": "المستفيد (اختياري)",
        "Payer": "صاحب الشيك",
        "Payer (optional)": "صاحب الشيك (اختياري)",
        "Account reference": "مرجع الحساب",
        "Account reference (optional)": "مرجع الحساب (اختياري)",
        "Notes": "ملاحظات",
        "Notes (optional)": "ملاحظات (اختياري)",
        "Not provided": "غير مسجّل",
        "Status": "الحالة",
        "Pending": "معلّق",
        "Collected": "تم التحصيل",
        "Paid": "تم الصرف",
        "Settled": "تم الصرف أو التحصيل",
        "Returned": "مرتجع",
        "Cancelled": "ملغى",
        "Overdue": "متأخر",
        "Change status": "تغيير الحالة",
        "Mark collected": "تأكيد التحصيل",
        "Mark paid": "تأكيد الصرف",
        "Mark returned": "تسجيل كمرتجع",
        "Mark cancelled": "إلغاء الشيك",
        "Mark pending": "إعادة إلى معلّق",
        "Collection date": "تاريخ التحصيل الفعلي",
        "Payment date": "تاريخ الصرف الفعلي",
        "Choose the date the cheque actually cleared.": "اختر التاريخ الذي تم فيه صرف الشيك أو تحصيله فعليًا.",
        "The actual payment or collection date cannot be in the future.": "تاريخ الصرف أو التحصيل الفعلي لا يمكن أن يكون في المستقبل.",
        "Everything in its time.": "كل المواعيد بين إيديك.",
        "A clear view of your next commitments.": "نظرة واضحة على التزاماتك القادمة.",
        "To collect": "للتحصيل",
        "To pay": "للدفع",
        "Outstanding cheques": "شيكات غير مسدّدة",
        "Outstanding only": "غير المسدّدة فقط",
        "Due today": "تستحق اليوم",
        "Within 7 days": "خلال 7 أيام",
        "Next 7 days": "الأيام السبعة القادمة",
        "Next cheques": "الشيكات القادمة",
        "See all": "عرض الكل",
        "A fresh start": "بداية مرتّبة",
        "Add your first cheque and let Shekati keep the dates in view.": "أضف شيكك الأول، وخلي مواعيدك واضحة مع شيكاتي.",
        "No cheques yet": "لا توجد شيكات بعد",
        "No outstanding cheques": "لا توجد شيكات غير مسدّدة",
        "Add a cheque to keep its dates and reminders here.": "أضف شيكًا لحفظ مواعيده وتذكيراته هنا.",
        "Add your first cheque to keep its details and reminders together.": "أضف شيكك الأول لحفظ معلوماته وتذكيراته في مكان واحد.",
        "No matching cheques": "لا توجد شيكات مطابقة",
        "Try another search or clear the filters.": "جرّب بحثًا آخر أو امسح الفلاتر.",
        "Search number, bank or name": "ابحث بالرقم أو البنك أو الاسم",
        "Clear search and filters": "مسح البحث والفلاتر",
        "Shown amount": "مجموع المبالغ المعروضة",
        "Total outstanding cheques": "إجمالي الشيكات غير المسدّدة",
        "Total exceeds supported range": "المجموع يتجاوز النطاق المدعوم",
        "View individual cheque amounts. Totals cannot be displayed accurately for these records.": "راجع مبلغ كل شيك بشكل منفصل. يتعذر عرض إجماليات دقيقة لهذه السجلات.",
        "Filters": "الفلاتر",
        "All": "الكل",
        "All banks": "كل البنوك",
        "All dates": "كل التواريخ",
        "Period": "الفترة",
        "From date": "من تاريخ",
        "Through date": "حتى تاريخ",
        "From": "من",
        "Through": "حتى",
        "Clear filters": "مسح الفلاتر",
        "Check the date range": "راجع الفترة المحددة",
        "The end date must be on or after the start date.": "تاريخ النهاية يجب أن يكون في تاريخ البداية أو بعده.",
        "Sort by": "ترتيب حسب",
        "Sort cheques": "ترتيب الشيكات",
        "Order": "اتجاه الترتيب",
        "Ascending": "تصاعدي",
        "Descending": "تنازلي",
        "Date added": "تاريخ الإضافة",
        "My order": "ترتيبي الخاص",
        "Drag cheques to change their order.": "اسحب الشيكات لتغيير ترتيبها.",
        "Your previous order was kept. Please try again.": "تم الاحتفاظ بترتيبك السابق. حاول مرة أخرى.",
        "Cheque images": "صور الشيك",
        "Cheque image": "صورة الشيك",
        "Front": "الوجه",
        "Back": "الخلف",
        "Scan": "تصوير",
        "Photos": "الصور",
        "Remove image": "إزالة الصورة",
        "Read details from front image": "قراءة معلومات صورة الوجه",
        "Review image details": "مراجعة معلومات الصورة",
        "Suggested details": "المعلومات المقترحة",
        "Recognized text": "النص المقروء",
        "Use selected": "استخدام المحدد",
        "Check each suggestion against your cheque. Nothing is saved until you tap Save.": "راجع كل اقتراح مع الشيك. لا يُحفظ شيء حتى تضغط حفظ.",
        "Some Arabic text may need manual entry. You can complete every field yourself.": "بعض النصوص العربية قد تحتاج إدخالًا يدويًا. يمكنك تعبئة جميع الحقول بنفسك.",
        "No fields were recognized. Keep entering the details manually.": "لم يتم التعرف على حقول واضحة. أكمل المعلومات يدويًا.",
        "Scan or choose an image, review the suggested details, then save the cheque.": "صوّر الشيك أو اختر صورته، وراجع المعلومات المقترحة، ثم احفظ الشيك.",
        "Camera unavailable": "الكاميرا غير متاحة",
        "You can choose an image from Photos or enter all cheque details manually. Allow camera access in Settings to scan.": "يمكنك اختيار صورة من الصور أو تعبئة المعلومات يدويًا. اسمح باستخدام الكاميرا من الإعدادات للتصوير.",
        "Open Settings": "فتح الإعدادات",
        "The image could not be read. You can enter all details manually.": "تعذرت قراءة الصورة. يمكنك تعبئة جميع المعلومات يدويًا.",
        "This image could not be opened. Try another image or enter the details manually.": "تعذر فتح الصورة. جرّب صورة أخرى أو أدخل المعلومات يدويًا.",
        "Check the details": "راجع المعلومات",
        "Enter a positive amount and the date written on the cheque.": "أدخل مبلغًا أكبر من صفر والتاريخ المكتوب على الشيك.",
        "Enter a valid amount greater than zero, using the currency’s decimal places.": "أدخل مبلغًا صحيحًا أكبر من صفر، وبعدد المنازل العشرية الخاص بالعملة.",
        "The issue date must be on or before the due date.": "تاريخ الإصدار يجب أن يكون في تاريخ الاستحقاق أو قبله.",
        "Choose the app currency in Settings before adding a cheque.": "اختر عملة التطبيق من الإعدادات قبل إضافة شيك.",
        "Resolve the currency setting before adding a cheque.": "راجع إعداد العملة قبل إضافة شيك.",
        "Could not save changes": "تعذر حفظ التغييرات",
        "Could not save changes.": "تعذر حفظ التغييرات.",
        "Your change was not saved. Please try again.": "لم يُحفظ التغيير. حاول مرة أخرى.",
        "Your previous details were kept. Please try again.": "تم الاحتفاظ بالمعلومات السابقة. حاول مرة أخرى.",
        "The cheque could not be saved. Your draft is still here; please try again.": "تعذر حفظ الشيك. بياناتك المدخلة ما زالت موجودة؛ حاول مرة أخرى.",
        "The cheque could not be deleted. Please try again.": "تعذر حذف الشيك. حاول مرة أخرى.",
        "Discard changes?": "تجاهل التغييرات؟",
        "Your unsaved changes will be lost.": "ستُفقد التغييرات التي لم تحفظها.",
        "Discard": "تجاهل",
        "Keep editing": "متابعة التعديل",
        "Reminders": "التذكيرات",
        "Reminders enabled": "التذكيرات مفعّلة",
        "Reminders disabled": "التذكيرات معطّلة",
        "Use default reminders": "استخدام التذكيرات الافتراضية",
        "Uses default reminders": "يستخدم التذكيرات الافتراضية",
        "Uses default reminder time": "يستخدم وقت التذكير الافتراضي",
        "The reminder days and time from Settings will be used.": "سيتم استخدام أيام التذكير ووقته من الإعدادات.",
        "3 days before": "قبل 3 أيام",
        "1 day before": "قبل يوم",
        "On due date": "في يوم الاستحقاق",
        "On the due date": "في يوم الاستحقاق",
        "Days before": "عدد الأيام قبل الاستحقاق",
        "Days before (1–365)": "أيام قبل الاستحقاق (1–365)",
        "Enter a whole number of days from 1 to 365.": "أدخل عدد أيام صحيحًا من 1 إلى 365.",
        "Choose at least one reminder day, or turn reminders off.": "اختر يوم تذكير واحدًا على الأقل، أو عطّل التذكيرات.",
        "No reminder days selected": "لم تُحدد أيام للتذكير",
        "Remove reminder": "إزالة التذكير",
        "Reminder time": "وقت التذكير",
        "Reminders stop when a cheque is settled or cancelled.": "تتوقف التذكيرات عند الصرف أو التحصيل أو الإلغاء.",
        "Reminders stop when a cheque is settled or cancelled. Past reminder times are skipped.": "تتوقف التذكيرات عند الصرف أو التحصيل أو الإلغاء. تُتجاوز أوقات التذكير التي مضت.",
        "Enable notifications": "تفعيل الإشعارات",
        "Notifications enabled": "الإشعارات مفعّلة",
        "Notifications are off": "الإشعارات معطّلة",
        "Enable notifications in Settings so your scheduled reminders can appear.": "فعّل الإشعارات من الإعدادات لتظهر تذكيراتك المجدولة.",
        "Enable in iPhone Settings": "التفعيل من إعدادات الآيفون",
        "Daily summary": "ملخص يومي",
        "Hide notification details": "إخفاء تفاصيل الإشعارات",
        "Scheduled notifications": "الإشعارات المجدولة",
        "First reminder not scheduled": "أول تذكير لم تتم جدولته",
        "Open the app before this time to renew the queue. Later reminders are not yet covered.": "افتح التطبيق قبل هذا الوقت لتجديد الجدولة. المواعيد التالية لم تُغطَّ بعد.",
        "Refresh reminders": "تحديث التذكيرات",
        "Refresh upcoming reminders": "جدّد تذكيرات المواعيد القادمة",
        "Open the app before": "افتح التطبيق قبل",
        "Some later reminders still need scheduling.": "بعض التذكيرات التالية ما زالت تحتاج جدولة.",
        "Some reminders could not be scheduled. Check permission and refresh the queue.": "تعذرت جدولة بعض التذكيرات. راجع الإذن وجدّد الجدولة.",
        "Defaults apply to cheques without custom reminders. Daily summaries include today and the next 3 days. Scheduled alerts work offline; a large queue needs periodic renewal.": "الإعدادات الافتراضية تُستخدم للشيكات دون تخصيص. الملخص يجمع اليوم والأيام الثلاثة التالية. التنبيهات المجدولة تعمل دون إنترنت؛ كثرة المواعيد تحتاج تجديدًا دوريًا.",
        "Appearance and language": "المظهر واللغة",
        "Language": "اللغة",
        "Appearance": "المظهر",
        "System": "حسب الجهاز",
        "Light": "فاتح",
        "Dark": "داكن",
        "Currency": "العملة",
        "Choose currency": "اختيار العملة",
        "Search currencies": "بحث عن عملة",
        "Currency cannot change while any saved cheque exists, including history.": "لا يمكن تغيير العملة مع وجود شيكات محفوظة، بما فيها السجل السابق.",
        "Your cheques.\nClearly organised.": "شيكاتك.\nمرتّبة وواضحة.",
        "Track what you owe and what you will collect, with timely reminders and everything in one place.": "تابع ما عليك وما إلك، مع تذكيرات بالمواعيد وكل المعلومات في مكان واحد.",
        "Know what is due": "اعرف مواعيد استحقاقك",
        "Scan, review, save": "صوّر، راجع، واحفظ",
        "Your records, with you": "سجلاتك بترافقك",
        "Choose one currency for your records. It stays fixed while saved cheques exist.": "اختر عملة واحدة لسجلاتك. تبقى ثابتة مع وجود شيكات محفوظة.",
        "Every cheque, at a glance.": "كل شيك، بنظرة واحدة.",
        "Different currencies found": "توجد عملات مختلفة",
        "Records from another device use a different currency. Resolve these records before adding new cheques. Totals are hidden to avoid mixing currencies.": "سجلات من جهاز آخر تستخدم عملة مختلفة. راجع هذه السجلات قبل إضافة شيكات جديدة. أُخفيت الإجماليات لمنع خلط العملات.",
        "Privacy": "الخصوصية",
        "Lock app": "قفل التطبيق",
        "Use Face ID, Touch ID or your device passcode. App previews are hidden when locking is enabled.": "استخدم بصمة الوجه أو الإصبع أو رمز الجهاز. تُحجب معاينة التطبيق عند تفعيل القفل.",
        "Device lock unavailable": "قفل الجهاز غير متاح",
        "Set a device passcode in iPhone Settings before enabling app lock.": "عيّن رمزًا للجهاز من إعدادات الآيفون قبل تفعيل قفل التطبيق.",
        "Your cheques, protected": "شيكاتك، بأمان",
        "Unlock to view your records": "افتح القفل لعرض سجلاتك",
        "Unlock": "فتح القفل",
        "Could not unlock. Try again using biometrics or your device passcode.": "تعذر فتح القفل. حاول باستخدام البصمة أو رمز الجهاز.",
        "iCloud": "iCloud",
        "Checking iCloud": "جارٍ التحقق من iCloud",
        "iCloud available": "iCloud متاح",
        "Syncing": "جارٍ المزامنة",
        "Synced": "تمت المزامنة",
        "Offline — saved on this iPhone": "دون إنترنت — محفوظ على هذا الآيفون",
        "Sign in to iCloud to sync": "سجّل الدخول إلى iCloud للمزامنة",
        "Sync paused — records remain on this iPhone": "المزامنة متوقفة — السجلات محفوظة على هذا الآيفون",
        "Local storage — restart to retry iCloud": "حفظ محلي — أعد التشغيل لمحاولة iCloud",
        "Simulator — local storage": "المحاكي — حفظ محلي",
        "Last sync": "آخر مزامنة",
        "Check iCloud status": "التحقق من حالة iCloud",
        "Cheques, photos, manual order and currency sync through your Apple account. Reminder defaults, language and lock are specific to this iPhone.": "الشيكات والصور والترتيب اليدوي والعملة تتزامن عبر حساب Apple. إعدادات التذكير العامة واللغة والقفل خاصة بهذا الآيفون.",
        "About": "عن التطبيق",
        "Version": "الإصدار",
        "All features included. One purchase. No subscription.": "كل الميزات مشمولة. شراء مرة واحدة دون اشتراك.",
        "Privacy policy": "سياسة الخصوصية",
        "Your records": "سجلاتك",
        "Cheque details and photos are stored on this iPhone. When iCloud is available, they sync to your private Apple account.": "معلومات الشيكات وصورها محفوظة على هذا الآيفون، وتتزامن مع حساب Apple الخاص بك عند توفر iCloud.",
        "Camera and text recognition": "الكاميرا وقراءة النصوص",
        "The camera is used only when you choose to scan. Text recognition happens on this iPhone. No cheque photo is sent to an external recognition service.": "تُستخدم الكاميرا عندما تختار التصوير. قراءة النصوص تتم على هذا الآيفون، ولا تُرسل الصور إلى خدمة قراءة خارجية.",
        "Notifications": "الإشعارات",
        "Reminders are scheduled on this device. You control permission, timing and whether cheque details appear in alerts.": "تُجدول التذكيرات على هذا الجهاز. أنت تتحكم بالإذن والمواعيد وظهور تفاصيل الشيك في الإشعار.",
        "App lock": "قفل التطبيق",
        "Authentication is handled by iOS. Shekati does not access or store your biometric information or device passcode.": "يتولى iOS التحقق من الهوية. لا يصل شيكاتي إلى معلومات البصمة أو رمز الجهاز ولا يحفظها.",
        "Your control": "التحكم ببياناتك",
        "You can edit or delete individual cheques. Deletions also sync to iCloud. iCloud sync is not a separate backup of deleted records.": "يمكنك تعديل الشيكات أو حذفها. الحذف يتزامن أيضًا مع iCloud؛ المزامنة ليست نسخة احتياطية منفصلة للسجلات المحذوفة.",
        "Analytics": "التحليلات",
        "Shekati includes no advertising or third-party analytics SDK. Apple may provide store and crash diagnostics according to your Apple settings.": "لا يتضمن شيكاتي إعلانات أو أدوات تحليل خارجية. قد توفر Apple إحصاءات المتجر وتقارير الأعطال حسب إعدادات حسابك.",
        "Unable to open your records": "تعذر فتح سجلاتك",
        "Your saved files were preserved. Restart the app and contact support if this continues.": "تم الاحتفاظ بالملفات المحفوظة. أعد تشغيل التطبيق وتواصل مع الدعم إذا استمرت المشكلة.",
        "Cheque saved. Enter the next cheque.": "تم حفظ الشيك. أدخل الشيك التالي.",
        "Confirm this due date": "تأكيد تاريخ الاستحقاق",
        "Review the due date for the next cheque.": "راجع تاريخ استحقاق الشيك التالي.",
        "Keep type, bank and name for the next cheque": "الاحتفاظ بالنوع والبنك والاسم للشيك التالي",
        "The next cheque always needs its own amount, number, photos and a reviewed due date.": "أدخل مبلغ الشيك التالي ورقمه وصوره، وراجع تاريخ استحقاقه.",
        "Save and add another": "حفظ وإضافة شيك آخر",
        "Next": "التالي",
        "Similar cheque found": "يوجد شيك مشابه",
        "View existing cheque": "عرض الشيك المحفوظ",
        "Save anyway": "حفظ رغم ذلك",
        "A similar cheque is already saved. Review it before adding another.": "يوجد شيك مشابه محفوظ. راجعه قبل إضافة شيك آخر.",
        "Used before": "استُخدم سابقًا",
        "Restore this cheque before changing it.": "استعد هذا الشيك قبل تعديله.",
        "Open reminder settings": "فتح إعدادات التذكير",
        "Next scheduled reminder": "التنبيه القادم المجدول",
        "No upcoming reminder is currently scheduled for this cheque.": "لا يوجد حاليًا تنبيه قادم مجدول لهذا الشيك.",
        "Daily summary is enabled; no individual reminder days are selected.": "الملخص اليومي مفعّل، ولم تُحدد أيام تنبيه منفردة.",
        "All individual reminder times for this cheque have passed.": "مرّت جميع مواعيد التنبيه المنفردة لهذا الشيك.",
        "The cheque moves to Recently Deleted for 30 days. Its reminders stop; you can restore its details and photos.": "يُنقل الشيك إلى المحذوفة مؤخرًا لمدة 30 يومًا، وتتوقف تنبيهاته. يمكنك استعادة تفاصيله وصوره.",
        "Cheque moved to Recently Deleted": "نُقل الشيك إلى المحذوفة مؤخرًا",
        "You can restore its details and photos for 30 days.": "يمكنك استعادة تفاصيله وصوره خلال 30 يومًا.",
        "Undo deletion": "تراجع عن الحذف",
        "Recently Deleted": "المحذوفة مؤخرًا",
        "The cheque could not be restored. Please try again.": "تعذرت استعادة الشيك. حاول مرة أخرى.",
        "Show cheques": "عرض الشيكات",
        "Outstanding": "غير مسدّدة",
        "All and history": "الكل والسجل",
        "Show all and history": "عرض الكل والسجل",
        "Shown incoming": "الوارد المعروض",
        "Shown outgoing": "الصادر المعروض",
        "Export this list as PDF": "تصدير هذه القائمة PDF",
        "Your data": "بياناتك",
        "Data and backup": "البيانات والنسخ الاحتياطي",
        "Recently deleted": "المحذوفة مؤخرًا",
        "Restore deleted cheques within 30 days. After that, only permanent deletion is available.": "يمكن استرجاع الشيكات المحذوفة خلال 30 يومًا. بعد ذلك يتوفر الحذف النهائي فقط.",
        "Permanent deletion also syncs to iCloud. Keep an independent backup if needed.": "يتزامن الحذف النهائي مع iCloud أيضًا. احتفظ بنسخة احتياطية مستقلة عند الحاجة.",
        "No deleted cheques": "لا توجد شيكات محذوفة",
        "Deleted": "تم الحذف",
        "Restore": "استرجاع",
        "Delete permanently": "حذف نهائي",
        "The 30-day restore period has ended.": "انتهت مهلة الاسترجاع البالغة 30 يومًا.",
        "Delete permanently?": "حذف نهائي؟",
        "This removes the cheque and its photos from this iPhone and iCloud. It cannot be undone.": "سيُحذف الشيك وصوره من هذا الآيفون وiCloud. لا يمكن التراجع عن ذلك.",
        "Backup": "النسخ الاحتياطي",
        "Create encrypted backup": "إنشاء نسخة احتياطية مشفّرة",
        "Restore backup": "استرجاع نسخة احتياطية",
        "A password-protected file includes every cheque, photo, reminder choice and deleted record. Keep the password safe; it cannot be recovered.": "يشمل الملف المحمي بكلمة مرور جميع الشيكات والصور وخيارات التذكير والسجلات المحذوفة. احتفظ بكلمة المرور بأمان؛ لا يمكن استعادتها.",
        "Excel and CSV": "Excel وCSV",
        "Import and export CSV": "استيراد وتصدير CSV",
        "CSV contains cheque details without photos. It can be opened in Excel. Review the file before importing.": "يحتوي CSV على تفاصيل الشيكات دون صور، ويمكن فتحه في Excel. راجع الملف قبل استيراده.",
        "Saved cheques": "الشيكات المحفوظة",
        "Backup password": "كلمة مرور النسخة الاحتياطية",
        "Confirm password": "تأكيد كلمة المرور",
        "Use at least 10 characters. Your password is not saved or sent anywhere.": "استخدم 10 أحرف على الأقل. لا تُحفظ كلمة المرور ولا تُرسل إلى أي جهة.",
        "Save encrypted backup": "حفظ النسخة المشفّرة",
        "Preparing file": "جارٍ تجهيز الملف",
        "Backup saved. Keep the file and password in a safe place.": "حُفظت النسخة الاحتياطية. احتفظ بالملف وكلمة المرور في مكان آمن.",
        "The file could not be saved. Please try again.": "تعذر حفظ الملف. حاول مرة أخرى.",
        "Could not complete operation": "تعذر إكمال العملية",
        "Choose backup file": "اختيار ملف النسخة الاحتياطية",
        "Review backup": "مراجعة النسخة الاحتياطية",
        "Opening backup": "جارٍ فتح النسخة الاحتياطية",
        "Restore preview": "معاينة الاسترجاع",
        "New cheques": "شيكات جديدة",
        "Unchanged cheques": "شيكات دون تغيير",
        "Existing cheques with changes": "شيكات موجودة بمعلومات مختلفة",
        "Deleted records in backup": "السجلات المحذوفة في النسخة",
        "Replace matching existing cheques": "استبدال الشيكات الموجودة المطابقة",
        "Off by default. New cheques are added; existing cheques remain unchanged. Turn on only to replace matching records with this backup's contents.": "مغلق افتراضيًا. تُضاف الشيكات الجديدة وتبقى الموجودة كما هي. فعّله فقط لاستبدال السجلات المطابقة بمعلومات هذه النسخة.",
        "Restore reviewed backup": "استرجاع النسخة بعد المراجعة",
        "Restore this backup?": "استرجاع هذه النسخة؟",
        "Review the counts and replacement choice. These changes will also sync to iCloud.": "راجع الأعداد وخيار الاستبدال. ستتزامن هذه التغييرات مع iCloud أيضًا.",
        "Backup restored": "تم استرجاع النسخة",
        "Export": "تصدير",
        "Export saved cheques to CSV": "تصدير الشيكات المحفوظة إلى CSV",
        "Exported files contain readable cheque details. Share only with people you choose.": "تحتوي الملفات المصدّرة على تفاصيل شيكات قابلة للقراءة. شاركها فقط مع من تختارهم.",
        "Import": "استيراد",
        "Download CSV template": "حفظ قالب CSV",
        "Choose CSV file": "اختيار ملف CSV",
        "Use the template's English column names, YYYY-MM-DD dates and your selected currency. Keep cheque numbers as text in Excel to preserve leading zeros.": "استخدم أسماء أعمدة القالب بالإنجليزية والتواريخ بصيغة YYYY-MM-DD والعملة المختارة. اجعل أرقام الشيكات نصًا في Excel للحفاظ على الأصفار في بدايتها.",
        "Import preview": "معاينة الاستيراد",
        "Valid rows": "الصفوف الصحيحة",
        "Rows with errors": "صفوف فيها أخطاء",
        "Possible duplicates": "تكرارات محتملة",
        "Include possible duplicates": "تضمين التكرارات المحتملة",
        "Import reviewed rows": "استيراد الصفوف بعد المراجعة",
        "Rows with errors are excluded. Possible duplicates are excluded unless you choose to include them. No cheque is saved before confirmation.": "تُستبعد الصفوف التي فيها أخطاء والتكرارات المحتملة ما لم تختر تضمينها. لا يُحفظ أي شيك قبل التأكيد.",
        "Rows": "الصفوف",
        "Possible duplicate": "تكرار محتمل",
        "Showing the first 200 rows. The counts include every row.": "تُعرض أول 200 صف. تشمل الأعداد جميع الصفوف.",
        "Import these cheques?": "استيراد هذه الشيكات؟",
        "Only the reviewed valid rows will be added. These changes will also sync to iCloud.": "ستُضاف الصفوف الصحيحة التي راجعتها فقط. ستتزامن هذه التغييرات مع iCloud أيضًا.",
        "Your records changed. Review the updated duplicate warnings before importing.": "تغيّرت سجلاتك. راجع تحذيرات التكرار المحدّثة قبل الاستيراد.",
        "Cheques imported": "تم استيراد الشيكات",
        "The file could not be read or saved. Please try again.": "تعذرت قراءة الملف أو حفظه. حاول مرة أخرى.",
        "This file is invalid or too large.": "هذا الملف غير صالح أو حجمه كبير جدًا.",
        "This backup version is not supported.": "إصدار هذه النسخة الاحتياطية غير مدعوم.",
        "The file contains invalid cheque information.": "يحتوي الملف على معلومات شيكات غير صحيحة.",
        "The file currency differs from your saved cheques.": "عملة الملف تختلف عن عملة الشيكات المحفوظة.",
        "Use a password of at least 10 characters.": "استخدم كلمة مرور من 10 أحرف على الأقل.",
        "The password is incorrect or the backup has been damaged.": "كلمة المرور غير صحيحة أو النسخة الاحتياطية تالفة.",
        "The number of columns does not match the header.": "عدد الأعمدة لا يطابق صف العناوين.",
        "Use incoming or outgoing, a positive amount and a valid YYYY-MM-DD date.": "استخدم incoming أو outgoing ومبلغًا موجبًا وتاريخًا صحيحًا بصيغة YYYY-MM-DD.",
        "Settled cheques need an actual date. Dates must use YYYY-MM-DD.": "تحتاج الشيكات المسدّدة إلى تاريخ فعلي. استخدم صيغة YYYY-MM-DD للتواريخ.",
        "The report includes the cheques and order shown in your filtered list.": "يشمل الكشف الشيكات وترتيبها كما تظهر في قائمتك المصفّاة.",
        "Save PDF report": "حفظ كشف PDF",
        "Save CSV of shown cheques": "حفظ الشيكات المعروضة بصيغة CSV",
        "Cheque report": "كشف الشيكات",
        "Deleted cheques can be restored for 30 days. Permanent deletion also syncs to iCloud. You can create an independent password-protected backup. CSV and PDF exports contain readable details; share them only when you choose.": "يمكن استرجاع الشيكات المحذوفة لمدة 30 يومًا. يتزامن الحذف النهائي مع iCloud أيضًا. يمكنك إنشاء نسخة احتياطية مستقلة محمية بكلمة مرور. تحتوي ملفات CSV وPDF المصدّرة على تفاصيل قابلة للقراءة؛ شاركها فقط عندما تختار ذلك.",
        "Tomorrow": "غدًا",
        "Restore reminder preferences": "استرجاع إعدادات التذكير",
        "This restores the default timing, daily summary and hidden notification details. Language and app lock stay as you set them on this iPhone.": "يسترجع هذا توقيت التذكيرات الافتراضي والملخص اليومي وإخفاء تفاصيل التنبيهات. تبقى اللغة وقفل التطبيق كما اخترتهما على هذا الآيفون.",
        "Issue date must not be after the due date or actual settlement date.": "يجب ألا يكون تاريخ الإصدار بعد تاريخ الاستحقاق أو تاريخ الصرف أو التحصيل الفعلي.",
        "Today": "اليوم",
        "Overdue by 1 day": "متأخر منذ يوم",
        "Overdue by 2 days": "متأخر منذ يومين",
        "In 2 days": "بعد يومين",
        "The actual payment or collection date cannot be before the issue date.": "لا يمكن أن يكون تاريخ الصرف أو التحصيل قبل تاريخ إصدار الشيك.",
        "Reviewing CSV": "جارٍ مراجعة CSV",
        "This cheque is no longer available": "هذا الشيك لم يعد متاحًا",
        "It was permanently deleted, possibly from another device.": "حُذف نهائيًا، وربما من جهاز آخر.",
        "This cheque was permanently deleted, possibly from another device. Your changes were not saved.": "حُذف هذا الشيك نهائيًا، وربما من جهاز آخر. لم تُحفظ التعديلات.",
        "Postdated cheques": "شيكات مؤجلة",
        "Value": "القيمة",
        "Pay to": "دائن الشيك",
        "Cheque no.": "رقم الشيك",
        "Cheque date": "تاريخ الصرف",
        "Balance": "رصيد",
        "No outgoing cheques": "لا توجد شيكات صادرة",
        "Outgoing cheques you add appear here in date order.": "تظهر هنا الشيكات الصادرة التي تضيفها مرتبة حسب التاريخ.",
        "Paid cheques": "المصروفة",
        "Free due dates": "الأيام الخالية",
        "Free days": "الأيام الخالية",
        "Select": "تحديد",
        "Select all": "تحديد الكل",
        "Clear selection": "إلغاء التحديد",
        "Selected": "محدّد",
        "Not selected": "غير محدّد",
        "Selected cheques": "الشيكات المحددة",
        "Selected total": "مجموع المحدد",
        "Select cheques in one currency": "حدّد شيكات بعملة واحدة",
        "Total unavailable": "المجموع غير متاح",
        "No paid cheques": "لا توجد شيكات مصروفة",
        "Paid cheques appear here with their details and payment dates.": "تظهر هنا الشيكات المصروفة مع تفاصيلها وتاريخ صرفها.",
        "Days with no unpaid outgoing cheques due, across all banks. Choose a period of up to 366 days.": "أيام لا تستحق فيها شيكات صادرة غير مسددة، في جميع البنوك. اختر فترة لا تتجاوز 366 يومًا.",
        "Choose a date range from today, with the end on or after the start, up to 366 days.": "اختر فترة تبدأ اليوم أو بعده وتنتهي في يوم البداية أو بعده، وبحد أقصى 366 يومًا.",
        "No free days in this period. Try another date range.": "لا توجد أيام خالية في هذه الفترة. جرّب فترة أخرى.",
        "Add an outgoing cheque on this day": "إضافة شيك صادر يستحق في هذا اليوم",
        "Tap a day to add an outgoing cheque with this due date.": "اضغط على يوم لإضافة شيك صادر بهذا الاستحقاق."
    ]
}
