import Foundation

enum Localization {
    static func text(_ key: String, language: AppLanguage) -> String {
        language == .arabic ? arabic[key] ?? key : key
    }

    static let arabic: [String: String] = [
        "Shekati": "شيكاتي",
        "Home": "الرئيسية",
        "Cheques": "الشيكات",
        "Settings": "الإعدادات",
        "Add cheque": "إضافة شيك",
        "Done": "تم",
        "Cancel": "إلغاء",
        "Save": "حفظ",
        "Save cheque": "حفظ الشيك",
        "Edit": "تعديل",
        "Edit cheque": "تعديل الشيك",
        "Delete": "حذف",
        "Delete cheque": "حذف الشيك",
        "Delete this cheque?": "حذف هذا الشيك؟",
        "Its details, images and scheduled reminders will be removed.": "سيتم حذف معلوماته وصوره وإزالة تنبيهاته المجدولة.",
        "OK": "حسنًا",
        "Add": "إضافة",
        "Apply": "تطبيق",
        "Required": "مطلوب",
        "Required details": "المعلومات المطلوبة",
        "Cheque": "شيك",
        "Cheque details": "تفاصيل الشيك",
        "Cheque number": "رقم الشيك",
        "Cheque number (optional)": "رقم الشيك (اختياري)",
        "No.": "رقم",
        "Incoming": "وارد",
        "Outgoing": "صادر",
        "Incoming cheque": "شيك وارد",
        "Outgoing cheque": "شيك صادر",
        "Direction": "نوع الشيك",
        "Amount": "المبلغ",
        "Name": "الاسم",
        "Due date": "تاريخ الاستحقاق",
        "Issue date": "تاريخ الإصدار",
        "Add issue date": "إضافة تاريخ الإصدار",
        "Bank": "البنك",
        "Bank (optional)": "البنك (اختياري)",
        "Branch": "الفرع",
        "Branch (optional)": "الفرع (اختياري)",
        "Payee": "المستفيد",
        "Payee (optional)": "المستفيد (اختياري)",
        "Payer": "صاحب الشيك",
        "Payer (optional)": "صاحب الشيك (اختياري)",
        "Account reference": "مرجع الحساب",
        "Account reference (optional)": "مرجع الحساب (اختياري)",
        "Notes": "ملاحظات",
        "Notes (optional)": "ملاحظات (اختياري)",
        "Not provided": "غير مسجّل",
        "Status": "الحالة",
        "Pending": "معلّق",
        "Collected": "تم التحصيل",
        "Paid": "تم الصرف",
        "Settled": "تم الصرف أو التحصيل",
        "Returned": "مرتجع",
        "Cancelled": "ملغى",
        "Overdue": "متأخر",
        "Change status": "تغيير الحالة",
        "Mark collected": "تأكيد التحصيل",
        "Mark paid": "تأكيد الصرف",
        "Mark returned": "تسجيل كمرتجع",
        "Mark cancelled": "إلغاء الشيك",
        "Mark pending": "إعادة إلى معلّق",
        "Collection date": "تاريخ التحصيل الفعلي",
        "Payment date": "تاريخ الصرف الفعلي",
        "Choose the date the cheque actually cleared.": "اختر التاريخ الذي تم فيه صرف الشيك أو تحصيله فعليًا.",
        "The actual payment or collection date cannot be in the future.": "تاريخ الصرف أو التحصيل الفعلي لا يمكن أن يكون في المستقبل.",
        "Everything in its time.": "كل المواعيد بين إيديك.",
        "A clear view of your next commitments.": "نظرة واضحة على التزاماتك القادمة.",
        "To collect": "للتحصيل",
        "To pay": "للدفع",
        "Outstanding cheques": "شيكات غير مسدّدة",
        "Outstanding only": "غير المسدّدة فقط",
        "Due today": "تستحق اليوم",
        "Within 7 days": "خلال ٧ أيام",
        "Next 7 days": "الأيام السبعة القادمة",
        "Next cheques": "الشيكات القادمة",
        "See all": "عرض الكل",
        "A fresh start": "بداية مرتّبة",
        "Add your first cheque and let Shekati keep the dates in view.": "أضف شيكك الأول، وخلي مواعيدك واضحة مع شيكاتي.",
        "No cheques yet": "لا توجد شيكات بعد",
        "Add your first cheque to keep its details and reminders together.": "أضف شيكك الأول لحفظ معلوماته وتذكيراته في مكان واحد.",
        "No matching cheques": "لا توجد شيكات مطابقة",
        "Try another search or clear the filters.": "جرّب بحثًا آخر أو امسح الفلاتر.",
        "Search number, bank or name": "ابحث بالرقم أو البنك أو الاسم",
        "Clear search and filters": "مسح البحث والفلاتر",
        "Shown amount": "مجموع المبالغ المعروضة",
        "Total outstanding cheques": "إجمالي الشيكات غير المسدّدة",
        "Total exceeds supported range": "المجموع يتجاوز النطاق المدعوم",
        "View individual cheque amounts. Totals cannot be displayed accurately for these records.": "راجع مبلغ كل شيك بشكل منفصل. يتعذر عرض إجماليات دقيقة لهذه السجلات.",
        "Filters": "الفلاتر",
        "All": "الكل",
        "All banks": "كل البنوك",
        "All dates": "كل التواريخ",
        "Period": "الفترة",
        "From date": "من تاريخ",
        "Through date": "حتى تاريخ",
        "From": "من",
        "Through": "حتى",
        "Clear filters": "مسح الفلاتر",
        "Check the date range": "راجع الفترة المحددة",
        "The end date must be on or after the start date.": "تاريخ النهاية يجب أن يكون في تاريخ البداية أو بعده.",
        "Sort by": "ترتيب حسب",
        "Sort cheques": "ترتيب الشيكات",
        "Order": "اتجاه الترتيب",
        "Ascending": "تصاعدي",
        "Descending": "تنازلي",
        "Date added": "تاريخ الإضافة",
        "My order": "ترتيبي الخاص",
        "Drag cheques to change their order.": "اسحب الشيكات لتغيير ترتيبها.",
        "Your previous order was kept. Please try again.": "تم الاحتفاظ بترتيبك السابق. حاول مرة أخرى.",
        "Cheque images": "صور الشيك",
        "Cheque image": "صورة الشيك",
        "Front": "الوجه",
        "Back": "الخلف",
        "Scan": "تصوير",
        "Photos": "الصور",
        "Remove image": "إزالة الصورة",
        "Read details from front image": "قراءة معلومات صورة الوجه",
        "Review image details": "مراجعة معلومات الصورة",
        "Suggested details": "المعلومات المقترحة",
        "Recognized text": "النص المقروء",
        "Use selected": "استخدام المحدد",
        "Check each suggestion against your cheque. Nothing is saved until you tap Save.": "راجع كل اقتراح مع الشيك. لا يُحفظ شيء حتى تضغط حفظ.",
        "Some Arabic text may need manual entry. You can complete every field yourself.": "بعض النصوص العربية قد تحتاج إدخالًا يدويًا. يمكنك تعبئة جميع الحقول بنفسك.",
        "No fields were recognized. Keep entering the details manually.": "لم يتم التعرف على حقول واضحة. أكمل المعلومات يدويًا.",
        "Scan or choose an image, review the suggested details, then save the cheque.": "صوّر الشيك أو اختر صورته، وراجع المعلومات المقترحة، ثم احفظ الشيك.",
        "Camera unavailable": "الكاميرا غير متاحة",
        "You can choose an image from Photos or enter all cheque details manually. Allow camera access in Settings to scan.": "يمكنك اختيار صورة من الصور أو تعبئة المعلومات يدويًا. اسمح باستخدام الكاميرا من الإعدادات للتصوير.",
        "Open Settings": "فتح الإعدادات",
        "The image could not be read. You can enter all details manually.": "تعذرت قراءة الصورة. يمكنك تعبئة جميع المعلومات يدويًا.",
        "This image could not be opened. Try another image or enter the details manually.": "تعذر فتح الصورة. جرّب صورة أخرى أو أدخل المعلومات يدويًا.",
        "Check the details": "راجع المعلومات",
        "Enter a positive amount and the date written on the cheque.": "أدخل مبلغًا أكبر من صفر والتاريخ المكتوب على الشيك.",
        "Enter a valid amount greater than zero, using the currency’s decimal places.": "أدخل مبلغًا صحيحًا أكبر من صفر، وبعدد المنازل العشرية الخاص بالعملة.",
        "The issue date must be on or before the due date.": "تاريخ الإصدار يجب أن يكون في تاريخ الاستحقاق أو قبله.",
        "Choose the app currency in Settings before adding a cheque.": "اختر عملة التطبيق من الإعدادات قبل إضافة شيك.",
        "Resolve the currency setting before adding a cheque.": "راجع إعداد العملة قبل إضافة شيك.",
        "Could not save changes": "تعذر حفظ التغييرات",
        "Could not save changes.": "تعذر حفظ التغييرات.",
        "Your change was not saved. Please try again.": "لم يُحفظ التغيير. حاول مرة أخرى.",
        "Your previous details were kept. Please try again.": "تم الاحتفاظ بالمعلومات السابقة. حاول مرة أخرى.",
        "The cheque could not be saved. Your draft is still here; please try again.": "تعذر حفظ الشيك. بياناتك المدخلة ما زالت موجودة؛ حاول مرة أخرى.",
        "The cheque could not be deleted. Please try again.": "تعذر حذف الشيك. حاول مرة أخرى.",
        "Discard changes?": "تجاهل التغييرات؟",
        "Your unsaved changes will be lost.": "ستُفقد التغييرات التي لم تحفظها.",
        "Discard": "تجاهل",
        "Keep editing": "متابعة التعديل",
        "Reminders": "التذكيرات",
        "Reminders enabled": "التذكيرات مفعّلة",
        "Reminders disabled": "التذكيرات معطّلة",
        "Use default reminders": "استخدام التذكيرات الافتراضية",
        "Uses default reminders": "يستخدم التذكيرات الافتراضية",
        "Uses default reminder time": "يستخدم وقت التذكير الافتراضي",
        "The reminder days and time from Settings will be used.": "سيتم استخدام أيام التذكير ووقته من الإعدادات.",
        "3 days before": "قبل ٣ أيام",
        "1 day before": "قبل يوم",
        "On due date": "في يوم الاستحقاق",
        "On the due date": "في يوم الاستحقاق",
        "days before": "أيام قبل الاستحقاق",
        "Days before": "عدد الأيام قبل الاستحقاق",
        "Days before (1–365)": "أيام قبل الاستحقاق (١–٣٦٥)",
        "Enter a whole number of days from 1 to 365.": "أدخل عدد أيام صحيحًا من ١ إلى ٣٦٥.",
        "Choose at least one reminder day, or turn reminders off.": "اختر يوم تذكير واحدًا على الأقل، أو عطّل التذكيرات.",
        "No reminder days selected": "لم تُحدد أيام للتذكير",
        "Remove reminder": "إزالة التذكير",
        "Reminder time": "وقت التذكير",
        "Reminders stop when a cheque is settled or cancelled.": "تتوقف التذكيرات عند الصرف أو التحصيل أو الإلغاء.",
        "Reminders stop when a cheque is settled or cancelled. Past reminder times are skipped.": "تتوقف التذكيرات عند الصرف أو التحصيل أو الإلغاء. تُتجاوز أوقات التذكير التي مضت.",
        "Enable notifications": "تفعيل الإشعارات",
        "Notifications enabled": "الإشعارات مفعّلة",
        "Notifications are off": "الإشعارات معطّلة",
        "Enable notifications in Settings so your scheduled reminders can appear.": "فعّل الإشعارات من الإعدادات لتظهر تذكيراتك المجدولة.",
        "Enable in iPhone Settings": "التفعيل من إعدادات الآيفون",
        "Daily summary": "ملخص يومي",
        "Hide notification details": "إخفاء تفاصيل الإشعارات",
        "Scheduled notifications": "الإشعارات المجدولة",
        "First reminder not scheduled": "أول تذكير لم تتم جدولته",
        "Open the app before this time to renew the queue. Later reminders are not yet covered.": "افتح التطبيق قبل هذا الوقت لتجديد الجدولة. المواعيد التالية لم تُغطَّ بعد.",
        "Refresh reminders": "تحديث التذكيرات",
        "Refresh upcoming reminders": "جدّد تذكيرات المواعيد القادمة",
        "Open the app before": "افتح التطبيق قبل",
        "Some later reminders still need scheduling.": "بعض التذكيرات التالية ما زالت تحتاج جدولة.",
        "Some reminders could not be scheduled. Check permission and refresh the queue.": "تعذرت جدولة بعض التذكيرات. راجع الإذن وجدّد الجدولة.",
        "Defaults apply to cheques without custom reminders. Daily summaries include today and the next 3 days. Scheduled alerts work offline; a large queue needs periodic renewal.": "الإعدادات الافتراضية تُستخدم للشيكات دون تخصيص. الملخص يجمع اليوم والأيام الثلاثة التالية. التنبيهات المجدولة تعمل دون إنترنت؛ كثرة المواعيد تحتاج تجديدًا دوريًا.",
        "Appearance and language": "المظهر واللغة",
        "Language": "اللغة",
        "Appearance": "المظهر",
        "System": "حسب الجهاز",
        "Light": "فاتح",
        "Dark": "داكن",
        "Currency": "العملة",
        "Choose currency": "اختيار العملة",
        "Search currencies": "بحث عن عملة",
        "Currency cannot change while any saved cheque exists, including history.": "لا يمكن تغيير العملة مع وجود شيكات محفوظة، بما فيها السجل السابق.",
        "Your cheques.\nClearly organised.": "شيكاتك.\nمرتّبة وواضحة.",
        "Track what you owe and what you will collect, with timely reminders and everything in one place.": "تابع ما عليك وما إلك، مع تذكيرات بالمواعيد وكل المعلومات في مكان واحد.",
        "Know what is due": "اعرف مواعيد استحقاقك",
        "Scan, review, save": "صوّر، راجع، واحفظ",
        "Your records, with you": "سجلاتك بترافقك",
        "Choose one currency for your records. It stays fixed while saved cheques exist.": "اختر عملة واحدة لسجلاتك. تبقى ثابتة مع وجود شيكات محفوظة.",
        "Every cheque, at a glance.": "كل شيك، بنظرة واحدة.",
        "Different currencies found": "توجد عملات مختلفة",
        "Records from another device use a different currency. Resolve these records before adding new cheques. Totals are hidden to avoid mixing currencies.": "سجلات من جهاز آخر تستخدم عملة مختلفة. راجع هذه السجلات قبل إضافة شيكات جديدة. أُخفيت الإجماليات لمنع خلط العملات.",
        "Privacy": "الخصوصية",
        "Lock app": "قفل التطبيق",
        "Use Face ID, Touch ID or your device passcode. App previews are hidden when locking is enabled.": "استخدم بصمة الوجه أو الإصبع أو رمز الجهاز. تُحجب معاينة التطبيق عند تفعيل القفل.",
        "Device lock unavailable": "قفل الجهاز غير متاح",
        "Set a device passcode in iPhone Settings before enabling app lock.": "عيّن رمزًا للجهاز من إعدادات الآيفون قبل تفعيل قفل التطبيق.",
        "Your cheques, protected": "شيكاتك، بأمان",
        "Unlock to view your records": "افتح القفل لعرض سجلاتك",
        "Unlock": "فتح القفل",
        "Could not unlock. Try again using biometrics or your device passcode.": "تعذر فتح القفل. حاول باستخدام البصمة أو رمز الجهاز.",
        "iCloud": "iCloud",
        "Checking iCloud": "جارٍ التحقق من iCloud",
        "iCloud available": "iCloud متاح",
        "Syncing": "جارٍ المزامنة",
        "Synced": "تمت المزامنة",
        "Offline — saved on this iPhone": "دون إنترنت — محفوظ على هذا الآيفون",
        "Sign in to iCloud to sync": "سجّل الدخول إلى iCloud للمزامنة",
        "Sync paused — records remain on this iPhone": "المزامنة متوقفة — السجلات محفوظة على هذا الآيفون",
        "Local storage — restart to retry iCloud": "حفظ محلي — أعد التشغيل لمحاولة iCloud",
        "Simulator — local storage": "المحاكي — حفظ محلي",
        "Last sync": "آخر مزامنة",
        "Check iCloud status": "التحقق من حالة iCloud",
        "Cheques, photos, manual order and currency sync through your Apple account. Reminder defaults, language and lock are specific to this iPhone.": "الشيكات والصور والترتيب اليدوي والعملة تتزامن عبر حساب Apple. إعدادات التذكير العامة واللغة والقفل خاصة بهذا الآيفون.",
        "About": "عن التطبيق",
        "Version": "الإصدار",
        "All features included. One purchase. No subscription.": "كل الميزات مشمولة. شراء مرة واحدة دون اشتراك.",
        "Privacy policy": "سياسة الخصوصية",
        "Your records": "سجلاتك",
        "Cheque details and photos are stored on this iPhone. When iCloud is available, they sync to your private Apple account.": "معلومات الشيكات وصورها محفوظة على هذا الآيفون، وتتزامن مع حساب Apple الخاص بك عند توفر iCloud.",
        "Camera and text recognition": "الكاميرا وقراءة النصوص",
        "The camera is used only when you choose to scan. Text recognition happens on this iPhone. No cheque photo is sent to an external recognition service.": "تُستخدم الكاميرا عندما تختار التصوير. قراءة النصوص تتم على هذا الآيفون، ولا تُرسل الصور إلى خدمة قراءة خارجية.",
        "Notifications": "الإشعارات",
        "Reminders are scheduled on this device. You control permission, timing and whether cheque details appear in alerts.": "تُجدول التذكيرات على هذا الجهاز. أنت تتحكم بالإذن والمواعيد وظهور تفاصيل الشيك في الإشعار.",
        "App lock": "قفل التطبيق",
        "Authentication is handled by iOS. Shekati does not access or store your biometric information or device passcode.": "يتولى iOS التحقق من الهوية. لا يصل شيكاتي إلى معلومات البصمة أو رمز الجهاز ولا يحفظها.",
        "Your control": "التحكم ببياناتك",
        "You can edit or delete individual cheques. Deletions also sync to iCloud. iCloud sync is not a separate backup of deleted records.": "يمكنك تعديل الشيكات أو حذفها. الحذف يتزامن أيضًا مع iCloud؛ المزامنة ليست نسخة احتياطية منفصلة للسجلات المحذوفة.",
        "Analytics": "التحليلات",
        "Shekati includes no advertising or third-party analytics SDK. Apple may provide store and crash diagnostics according to your Apple settings.": "لا يتضمن شيكاتي إعلانات أو أدوات تحليل خارجية. قد توفر Apple إحصاءات المتجر وتقارير الأعطال حسب إعدادات حسابك.",
        "Unable to open your records": "تعذر فتح سجلاتك",
        "Your saved files were preserved. Restart the app and contact support if this continues.": "تم الاحتفاظ بالملفات المحفوظة. أعد تشغيل التطبيق وتواصل مع الدعم إذا استمرت المشكلة."
    ]
}
